server:
  port: 8781
spring:
  application:
    name: zeus-admin
  security:
    user:
      name: admin
      password: admin
  admin:
    ding-talk-token: 7b78714f7c351d6891eab4e81bc79b1533586c3a20e50ecb82e506c27c819f6f
eureka:
  instance:
    prefer-ip-address: true
    instance-id: zeus-admin
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2
    ip-address: ${EUREKA_INSTANCE_IP_ADDRESS:127.0.0.1}
    health-check-url-path: /actuator/health
    metadata-map:
      user.name: "admin"
      user.password: "admin"
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://admin:admin@${ZEUS_EUREKA_HOST_1:127.0.0.1}:8761/eureka,http://admin:admin@${ZEUS_EUREKA_HOST_2:127.0.0.1}:8762/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
