server:
  port: 8089
spring:
  application:
    name: zeus-admin
  security:
    user:
      name: admin
      password: admin
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      user.name: "admin"
      user.password: "admin"
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://admin:admin@${ZEUS_EUREKA_HOST_1:127.0.0.1}:8761/eureka,http://admin:admin@${ZEUS_EUREKA_HOST_2:127.0.0.1}:8762/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
