server:
  port: 8771
spring:
  application:
    name: zeus-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/lollipopDevil/zeus-config.git # 配置git仓库的地址
          username: zhangtong9498@qq.com
          password: devil1994
          search-paths: repo
          default-label: master
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:127.0.0.1}
    port: 5672
    username: ${SPRING_RABBITMQ_USERNAME:admin}
    password: ${SPRING_RABBITMQ_PASSWORD:admin}
    virtual-host: zeus
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin@${ZEUS_EUREKA_HOST_1:127.0.0.1}:8761/eureka,http://admin:admin@${ZEUS_EUREKA_HOST_2:127.0.0.1}:8762/eureka
  instance:
    prefer-ip-address: true
    instance-id: zeus-config
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2
    ip-address: ${EUREKA_INSTANCE_IP_ADDRESS:127.0.0.1}
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

