version: '3'
services:
  zeus-transfer:
    container_name: zeus-transfer
    image: registry.cn-hangzhou.aliyuncs.com/zt_images/zeus-transfer:latest
    ports:
      - '8898:8898'
    volumes:
      - ./zeus-transfer/data/log:/log:rw
#      - /etc/localtime:/etc/localtime:ro
      - /logs/:/logs/:rw
    env_file:
      - zeus-transfer/env/zeus-transfer.env
    depends_on:
      - mysql-zeus-transfer
    environment:
      - ZEUS_EUREKA_HOST_1=192.168.30.11
      - ZEUS_EUREKA_HOST_2=192.168.30.11
      - SPRING_CLOUD_CONFIG_NAME=zeus
      - SPRING_CLOUD_CONFIG_PROFILE=tsgz
      - EUREKA_INSTANCE_IP_ADDRESS=210.13.50.104
      - CUSTOM_QUARTZ_CORN=0 30 * * *  ?
  mysql-zeus-transfer:
    container_name: mysql-zeus-transfer
    image: mysql:8.0.23
    env_file:
      - mysql-zeus-transfer/env/mysql.env
    volumes:
      - ./mysql-zeus-transfer/db:/var/lib/mysql
      - ./mysql-zeus-transfer/conf:/etc/mysql/conf.d
      - ./mysql-zeus-transfer/logs:/logs
      - ./mysql-zeus-transfer/init/:/docker-entrypoint-initdb.d/
#      - /etc/localtime:/etc/localtime:rw
    ports:
      - '3307:3306'

