server:
  port: 8899
spring:
  application:
    name: zeus-transfer-local
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://${SPRING_DATASOURCE_URL:127.0.0.1}:3306/pull-push?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&&serverTimezone=UTC
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    hikari:
      connection-timeout: 30000
      max-lifetime: 1800000
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    open-in-view: false
  quartz:
    #相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    job-store-type: MEMORY
  security:
    user:
      name: admin #账号
      password: admin  #密码
management:
  endpoints:
    web:
      exposure:
        include: 'loggers'
  endpoint:
    health:
      show-details: always
logging:
  file:
    name: /logs/${spring.application.name}/${spring.application.name}.log
custom:
  custom-word:
    word:
      - 中国
    author:
      - 环球网
    carrier:
      - WE_CHAT
      - MICRO_BLOG
  es:
    version: 5
    page-size: 500
    file-path: D:\test2
    read-model: File
    analysis: http://127.0.0.1:8081
    search-type: EXACT
    es5: #es配置信息
      #      key: yq_test
      key: yq_zkdj
      host: http://river.junquan.com.cn
      app-id: 1231231
      full-query: /river/river/dataQuery
  #      full-query: /restserver/river/dataQuery
  quartz:
    #    每隔5秒执行一次：*/5 * * * * ?
    #    每隔1分钟执行一次：0 */1 * * * ?
    #    每天23点执行一次：0 0 23 * * ?
    #    每天凌晨1点执行一次：0 0 1 * * ?
    #    每月1号凌晨1点执行一次：0 0 1 1 * ?
    #    每月最后一天23点执行一次：0 0 23 L * ?
    #    每周星期天凌晨1点实行一次：0 0 1 ? * L
    #    在26分、29分、33分执行一次：0 26,29,33 * * * ?
    #    每天的0点、13点、18点、21点都执行一次：0 0 0,13,18,21 * * ?
    corn: 0 */1 * * * ?
    #    YEAR, MONTH, DAY, HOUR, MINUTE, SECOND,
    time-type: MINUTE
    #    开始时间提前多少 需要跟corn对应
    time-range: -999
    #    CUSTOM_AUTHOR(自定义作者) CUSTOM_WORD(自定义词) GATHER_WORD（词库中gather表）GATHER_AUTHOR（词库中author表） PUSH_ARTICLE 推送
    job-Type:
      - CUSTOM_WORD
    #    true 开启  false 关闭
    state: false

