server:
  port: 8899
spring:
  application:
    name: zeus-transfer-local
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://${SPRING_DATASOURCE_URL:127.0.0.1}:3306/pull-push?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&&serverTimezone=UTC
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    hikari:
      connection-timeout: 30000
      max-lifetime: 1800000
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    open-in-view: false
  quartz:
    #相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    job-store-type: MEMORY
  security:
    user:
      name: admin #账号
      password: admin  #密码
management:
  endpoints:
    web:
      exposure:
        include: 'loggers'
  endpoint:
    health:
      show-details: always
logging:
  file:
    name: /logs/${spring.application.name}/${spring.application.name}.log
custom:
  query:
    related-query:
      related: ${CUSTOM_QUERY_RELATED_QUERY_WORD:[中国,美国]}
      carrier: ${CUSTOM_QUERY_RELATED_QUERY_CARRIER:}
    author-query:
      author: ${CUSTOM_QUERY_AUTHOR_QUERY_AUTHOR:[中国,美国]}
      carrier: ${CUSTOM_QUERY_AUTHOR_QUERY_CARRIER:[WE_CHAT]}
  es:
    version: 5
    page-size: ${CUSTOM_ES_PAGE_SIZE:500}
    file-path: ${CUSTOM_ES_FILE_PATH:/word}
    read-model: ${CUSTOM_ES_READ_MODEL:File}
    analysis: ${CUSTOM_ES_ANALYSIS:http://127.0.0.1:8081}
    search-type: ${CUSTOM_ES_SEARCH_TYPE:EXACT}
    search-range: PUBLISH_TIME
    es5: #es配置信息
      #      key: yq_test
      key: ${CUSTOM_ES_ES5_KEY:yq_zkdj}
      host: ${CUSTOM_ES_ES5_HOST:http://river.junquan.com.cn}
      app-id: 1231231
      full-query: ${CUSTOM_ES_ES5_FULL_QUERY:/river/river/dataQuery}
      article-query: ${CUSTOM_ES_ES5_ARTICLE_QUERY:/index/query/queryByIdsWithContent}
  quartz:
    corn: ${CUSTOM_QUARTZ_CORN:0 */1 * * * ?}
    #    YEAR, MONTH, DAY, HOUR, MINUTE, SECOND,
    time-type: ${CUSTOM_QUARTZ_TIME_TYPE:MINUTE}
    #    开始时间提前多少 需要跟corn对应
    time-range: ${CUSTOM_QUARTZ_TIME_RANGE:-999}
    #    CUSTOM_AUTHOR(自定义作者) CUSTOM_WORD(自定义词) GATHER_WORD（词库中gather表）GATHER_AUTHOR（词库中author表） PUSH_ARTICLE 推送
    job-Type: ${CUSTOM_QUARTZ_JOB_TYPE:CUSTOM_WORD}
    #    true 开启  false 关闭
    state: ${CUSTOM_QUARTZ_STATE:false}

