version: '3'
services:
  zeus-transfer-local:
    container_name: zeus-transfer-local
    image: registry.cn-hangzhou.aliyuncs.com/zt_images/zeus-transfer-local:latest
    ports:
      - '8899:8899'
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - /logs/:/logs/:rw
    env_file:
      - zeus-transfer/env/zeus-transfer.env
    depends_on:
      - mysql-zeus-transfer
  mysql-zeus-transfer:
    container_name: mysql-zeus-transfer
    image: mysql:8.0.23
    env_file:
      - mysql-zeus-transfer/env/mysql.env
    volumes:
      - ./mysql-zeus-transfer/db:/var/lib/mysql
      - ./mysql-zeus-transfer/conf:/etc/mysql/conf.d
      - ./mysql-zeus-transfer/logs:/logs
      - ./mysql-zeus-transfer/init/:/docker-entrypoint-initdb.d/
#      - /etc/localtime:/etc/localtime:rw
    ports:
      - '3307:3306'

